version: "3"

services:
  mysql:
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  test-db:
    image: mysql:8
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local